### ISSUE TITLE
Reading Time on blog index

### ISSUE THREAD

**Issue by ferrarafer** [hellotham/hello-astro#17]
Hello, I just cloned the repository and when I run it I'm not seeing the reading time of each post on blog path but on your [website](https://hellotham.github.io/hello-astro/blog/) is there, do you know why?

Thanks in advance!

**Comment by ChristineTham** [comment]
> Hello, I just cloned the repository and when I run it I'm not seeing the reading time of each post on blog path but on your [website](https://hellotham.github.io/hello-astro/blog/) is there, do you know why?
> 
> Thanks in advance!

Unfortunately I had to take this feature out when the starter transitioned to using collections, as reading time has not yet been calculated when calling GetCollection(). To reimplement this feature would require bypassing collections or manually invoking markdown parsing when displaying a collection of blog pages. Let me know if you have any suggestions on this matter. Also, Markdoc pages do not currently process remark plugins including the reading time calculator.
