### ISSUE TITLE
This theme just not work with node v19.4.0. Also, has a duplicate MDX entry

### ISSUE THREAD

**Issue by alejovargas** [hellotham/hello-astro#2]
❯ pnpm i
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
 WARN  deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
Packages: +589
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/alejo/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 630, reused 589, downloaded 0, added 589, done

dependencies:
+ @astrojs/rss 1.2.1 (2.0.0 is available)
+ astro-icon 0.7.3 (0.8.0 is available)
+ astro-seo 0.6.1
+ hero-patterns 2.1.0
+ katex 0.16.4
+ leaflet 1.9.3
+ lunr 2.3.9
+ photoswipe 5.3.4
+ photoswipe-dynamic-caption-plugin 1.2.7

devDependencies:
+ @akebifiky/remark-simple-plantuml 1.0.2
+ @astrojs/alpinejs 0.1.2
+ @astrojs/image 0.10.0 (0.12.1 is available)
+ @astrojs/mdx 0.11.6 (0.14.0 is available)
+ @astrojs/sitemap 1.0.0
+ @astrojs/tailwind 2.1.3
+ @tailwindcss/aspect-ratio 0.4.2
+ @tailwindcss/forms 0.5.3
+ @tailwindcss/line-clamp 0.4.2
+ @tailwindcss/typography 0.5.9
+ @types/alpinejs 3.7.1
+ @types/leaflet 1.9.0
+ alpinejs 3.10.5
+ astro 1.5.2 (1.8.0 is available)
+ astro-robots-txt 0.3.11
+ exifr 7.1.3
+ mdast-util-to-string 3.1.0
+ prettier-plugin-astro 0.6.0 (0.7.2 is available)
+ reading-time 1.5.0
+ rehype-katex 6.0.2
+ remark-math 5.1.1
+ schema-dts 1.1.0
+ tailwindcss 3.2.4
+ unist-util-visit 4.1.1

 WARN  Issues with peer dependencies found
.
├─┬ @astrojs/mdx 0.11.6
│ └─┬ @mdx-js/rollup 2.2.1
│   ├── ✕ missing peer rollup@>=2
│   └─┬ @rollup/pluginutils 5.0.2
│     └── ✕ missing peer rollup@^1.20.0||^2.0.0||^3.0.0
└─┬ schema-dts 1.1.0
  └── ✕ missing peer typescript@>=4.1.0
Peer dependencies that should be installed:
  rollup@">=2.0.0 <3.0.0 || >=3.0.0 <4.0.0"
  typescript@>=4.1.0

Done in 12.4s
❯ pnpm run dev

> hello-astro@1.0.1 dev /Users/alejo/Documents/Code/GitHub-i7.tmp/test/hello-astro
> astro dev

[MDX] Now inheriting remark and rehype plugins from "markdown" config.
If you applied a plugin to both your Markdown and MDX configs, we suggest removing the duplicate MDX entry.
See "extendPlugins" option to configure this behavior.
  🚀  astro  v1.5.2 started in 473ms
  
  ┃ Local    http://localhost:3000/hello-astro/
  ┃ Network  use --host to expose
  
/Users/alejo/Documents/Code/GitHub-i7.tmp/test/hello-astro/node_modules/.pnpm/web-streams-polyfill@3.2.1/node_modules/web-streams-polyfill/dist/polyfill.js:362
            throw new TypeError(context + " is not a ReadableStream.");
                  ^

TypeError: First parameter has member 'readable' that is not a ReadableStream.
    at assertReadableStream (/Users/alejo/Documents/Code/GitHub-i7.tmp/test/hello-astro/node_modules/.pnpm/web-streams-polyfill@3.2.1/node_modules/web-streams-polyfill/dist/polyfill.js:362:19)
    at convertReadableWritablePair (/Users/alejo/Documents/Code/GitHub-i7.tmp/test/hello-astro/node_modules/.pnpm/web-streams-polyfill@3.2.1/node_modules/web-streams-polyfill/dist/polyfill.js:3524:9)
    at ReadableStream.pipeThrough (/Users/alejo/Documents/Code/GitHub-i7.tmp/test/hello-astro/node_modules/.pnpm/web-streams-polyfill@3.2.1/node_modules/web-streams-polyfill/dist/polyfill.js:3608:29)
    at fetchFinale (node:internal/deps/undici/undici:13682:56)
    at mainFetch (node:internal/deps/undici/undici:13574:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by ChristineTham** [comment]
Hi - thanks for posting this issue.

The error is related to an upstream package, and is not part of the source code of this theme, or astro. The theme does build in node 18 - I just checked.

The warning relating to "duplicate MDX entry" is just a precautionary warning - there is no separate MDX and Markdown configs in the config. It has been removed in later versions of astro.

**Comment by alejovargas** [comment]
Thank you Christine
