### ISSUE TITLE
Mermaid doesn't work

### ISSUE THREAD

**Issue by torn4dom4n** [hellotham/hello-astro#25]
Visit https://hellotham.github.io/hello-astro/blog/2022-08-20-mermaid-diagrams/ and looks like Mermaid Diagrams are broken.

![image](https://github.com/hellotham/hello-astro/assets/27698189/c9f8f2f4-fddb-442f-a75d-0cf1b9ff3707)

I'm use MS Edge v119.0.2151.72

**Comment by ChristineTham** [comment]
My apologies, it looks like Mermaid v9 no longer loads from CDN. I've fixed it by loading the latest version of Mermaid. Hopefully if you sync the codebase, it will work for you as well.
